### ISSUE TITLE
alignment error in mobile view

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#629]
### screenshot:

![Screenshot from 2020-02-24 20-52-09](https://user-images.githubusercontent.com/54955755/75165208-0b799280-5748-11ea-9ad4-edc6269358b8.png)

## Additional context
I would like to take this issue

**Comment by annatuma** [comment]
It is possible that this has been addressed in https://github.com/creativecommons/cccatalog-frontend/pull/628 but we will only see that after the pull request is merged. The screenshots are missing "back to search results" for the "After" version.

Assigning to @akmadian for now. Once #628 is merged, if this is still an issue, then it is fine to proceed with left alignment of the "back to search results" link.

**Comment by akmadian** [comment]
AFAIK, this hasn't been changed in 628. Although I would like to know more about what you mean by "padding error". Do you mean that it should be left more to be aligned with the left edge of the image?

I'll add `requires ticket work` until you respond with more details, and I'll remove `not ready for work` since this is not changed in 628 :)

**Comment by coderbabu10** [comment]
yes! i think in the mobile view it should be more towards left align with the photo.
@akmadian

**Comment by akmadian** [comment]
Sounds good, and I agree! I'm going to re-add `not ready for work` and `blocked` because there are two relatively large PRs that make lots of styling changes open right now (see #628 and #661).

Once those two are merged, we can come back to this if it's still an issue.

**Comment by akmadian** [comment]
Thanks for reporting this @coderbabu10, this is still an issue so you may go ahead and work on it!

**Comment by abhisheknaiidu** [comment]
Changing alignment with respect to this image does makes sense actually, because images were opening different and taking different frames for different orientations like for vertical images,the given alignment will be fine, but for horizontal images there might be an issue which @coderbabu10  has addressed, 

But after the new design got merged, this issue is fixed by great extent and it can be closed now @brenoferreira @kgodey
